version: '1.1'
services:
  main:
    image: staslabanov/main-task1
    build: .
    ports:
      - "3000:3000"
  date:
    image: staslabanov/main-task1-date
    build:
      dockerfile: date.dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - main
