version: '1'
services:
  main:
    image: staslabanov/main-task1
    build:
      dockerfile: Dockerfile
    ports:
      - "1000:3000"
  date:
    image: staslabanov/main-task1-date
    build:
      dockerfile: date.dockerfile
    ports:
      - "1005:3005"
    depends_on:
      - main
