version: '1'
services:
  main:
    image: staslabanov/main-task1
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  date:
    image: staslabanov/main-task1-date
    build:
      dockerfile: date.dockerfile
    depends_on:
      - main
